import{pageHeader,$,$all,toast}from'../ui.js';
import{isMobileView}from'../view.js';
import{escapeHtml}from'../utils.js';

const topics=[
 ['▤','Cómo subir una factura','Registra tus facturas en segundos y mantenlas organizadas.',['Toca en Subir factura desde el inicio.','Selecciona la imagen o PDF desde tu galería.','Completa monto, fecha, responsable, proyecto y proveedor.','La factura quedará disponible en el historial.']],
 ['▱','Cómo evitar duplicados','La verificación combina varios datos para reducir errores.',['Proveedor y número de factura generan una clave normalizada.','El hash detecta el mismo archivo aunque cambie de nombre.','Las compras sin comprobante solo muestran una alerta.','Un duplicado exacto requiere justificación para continuar.']],
 ['●','Cómo crear recordatorios','Crea una nota rápida cuando no puedas completar el formulario.',['Escribe únicamente qué se compró.','Completar abre el formulario con la descripción precargada.','Posponer mueve el próximo aviso.','Cancelar conserva el motivo y la trazabilidad.']],
 ['$','Cómo solicitar monto','Una solicitud es un mensaje y no modifica el flujo.',['Selecciona destinatario, monto, proyecto y motivo.','Puedes guardar un borrador durante la sesión.','El saldo cambia únicamente después de una transferencia confirmada.']],
 ['⇄','Cómo enviar una transferencia','Envía el aviso con referencia y evidencia.',['Selecciona al beneficiario.','Adjunta el comprobante bancario.','El destinatario puede confirmar o rechazar.','Una confirmación crea el ingreso contable.']],
 ['⌁','Cómo interpretar el flujo','El saldo se reconstruye desde movimientos auditables.',['Los ingresos suman y los egresos restan.','Los ajustes corrigen diferencias sin borrar historia.','Los reversos crean un movimiento inverso.','El saldo sincronizado refleja lo confirmado en la nube.']],
 ['☷','Personalizar formularios','El administrador decide qué campos aparecen y en qué orden.',['Abre Configuración y entra en Formularios.','Usa Vista simple para reducir pasos durante el piloto.','Los campos ocultos conservan valores automáticos.','Exporta la configuración para repetirla en otro dispositivo o futura APK.']],
 ['↗','Microsoft Graph, OneDrive y Outlook','Conecta una cuenta Microsoft sin guardar Client Secret en el navegador.',['Registra una aplicación SPA en Microsoft Entra.','Pega Tenant ID y Client ID en Integraciones.','Conectar cuenta utiliza OAuth con PKCE.','OneDrive almacena evidencias y Outlook puede enviar avisos.']],
 ['☁','Respaldos y sincronización','Protege la información local y comparte datos cuando corresponda.',['IndexedDB guarda los datos en este navegador.','El respaldo JSON puede incluir evidencias.','Supabase permite el modo multiusuario.','Nunca subas facturas al repositorio de GitHub Pages.']]
];
function mobileManual(){return`<div class="mobile-page"><div class="mobile-manual-search"><input id="manualSearch" type="search" placeholder="Buscar ayuda"></div><div id="manualTopics" class="mobile-list">${topics.map((t,i)=>`<details class="mobile-accordion" ${i===0?'open':''} data-manual-topic="${escapeHtml(t[1].toLowerCase())}"><summary><span class="mobile-icon-box ${i===0?'purple':i===1?'green':i===2?'orange':''}">${t[0]}</span><strong>${escapeHtml(t[1])}</strong><span>⌄</span></summary><div class="mobile-accordion-content"><p>${escapeHtml(t[2])}</p><ul>${t[3].map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div></details>`).join('')}</div><button class="mobile-secure" id="contactSupport" type="button"><span class="mobile-icon-box">☊</span><span><strong>Contactar soporte</strong><small>Abre tu aplicación de correo para solicitar ayuda.</small></span><span>›</span></button></div>`}
function desktopManual(){return`${pageHeader('Manual de uso','Guía práctica de la versión web compatible con GitHub Pages.','','Ayuda')}<section class="grid grid-2">${topics.map((t,i)=>`<article class="card"><div class="card-header"><h2>${i+1}. ${escapeHtml(t[1].replace(/^Cómo /,''))}</h2></div><div class="card-body stack"><p>${escapeHtml(t[2])}</p>${t[3].map(x=>`<p>${escapeHtml(x)}</p>`).join('')}</div></article>`).join('')}</section><section class="card" style="margin-top:18px"><div class="card-header"><h2>Regla clave</h2></div><div class="card-body"><div class="alert alert-warning"><strong>No utilice GitHub Pages como base de datos.</strong> No suba facturas reales ni respaldos al repositorio.</div></div></section>`}
export function renderManual(app){app.innerHTML=isMobileView()?mobileManual():desktopManual();$('#manualSearch',app)?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();$all('[data-manual-topic]',app).forEach(x=>x.hidden=q&&!x.dataset.manualTopic.includes(q))});$('#contactSupport',app)?.addEventListener('click',()=>{location.href='mailto:soporte@skc.local?subject=Soporte%20SKC%20Facturas';toast('Se abrió el correo de soporte.','success')})}
